-- ============================================================================
-- Matrimony Seed Data
-- 100 records across all tables for testing and development
-- ============================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- USERS (100 records)
INSERT IGNORE INTO users (email, password_hash, is_active, is_verified, last_login_at) VALUES
('rahul.sharma@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('priya.singh@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('amit.kumar@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('neha.verma@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('vikram.patel@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('anita.gupta@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('rajesh.mehta@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 7 DAY)),
('sunita.jain@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('deepak.sharma@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 9 DAY)),
('pooja.agarwal@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 10 DAY)),
('suresh.kumar@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 11 DAY)),
('rekha.singh@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 12 DAY)),
('manoj.verma@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 13 DAY)),
('kavita.rao@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 14 DAY)),
('sunil.reddy@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 15 DAY)),
('laxmi.nair@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 16 DAY)),
('ramesh.iyer@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 17 DAY)),
('meena.krishnan@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 18 DAY)),
('arun.pillai@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 19 DAY)),
('divya.menon@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 20 DAY)),
('venkat.raju@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 21 DAY)),
('sneha.devi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 22 DAY)),
('krishna.murthy@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 23 DAY)),
('padma.lakshmi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 24 DAY)),
('narendra.sharma@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 25 DAY)),
('savita.gupta@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 26 DAY)),
('mohan.singh@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 27 DAY)),
('ashwini.kumar@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 28 DAY)),
('pradeep.yadav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 29 DAY)),
('meenakshi.devi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 30 DAY)),
('ajay.dubey@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 31 DAY)),
('rani.trivedi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 32 DAY)),
('vijay.tiwari@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 33 DAY)),
('geeta.pande@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 34 DAY)),
('sanjay.mishra@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 35 DAY)),
('anuradha.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 36 DAY)),
('harsh.vora@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 37 DAY)),
('bhavana.shah@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 38 DAY)),
('dinesh.desai@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 39 DAY)),
('jyoti.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 40 DAY)),
('subhash.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 41 DAY)),
('madhuri.pawar@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 42 DAY)),
('prakash.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 43 DAY)),
('swati.shinde@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 44 DAY)),
('mahesh.kamble@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 45 DAY)),
('priyanka.salve@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 46 DAY)),
('sandeep.more@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 47 DAY)),
('archana.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 48 DAY)),
('rahul.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 49 DAY)),
('nisha.gore@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 50 DAY)),
('atul.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 51 DAY)),
('pallavi.deshmukh@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 52 DAY)),
('nikhil.suryawanshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 53 DAY)),
('rashmi.pawar@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 54 DAY)),
('abhishek.bhosale@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 55 DAY)),
('shweta.kadam@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 56 DAY)),
('rohit.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 57 DAY)),
('tejaswini.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 58 DAY)),
('omkar.shinde@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 59 DAY)),
('sayali.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 60 DAY)),
('kiran.gawade@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 61 DAY)),
('megha.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 62 DAY)),
('sachin.deshpande@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 63 DAY)),
('shraddha.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 64 DAY)),
('prasad.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 65 DAY)),
('anuja.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 66 DAY)),
('milind.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 67 DAY)),
('prachi.deshmukh@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 68 DAY)),
('saurabh.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 69 DAY)),
('neelam.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 70 DAY)),
('amol.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 71 DAY)),
('vaishali.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 72 DAY)),
('pravin.deshpande@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 73 DAY)),
('supriya.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 74 DAY)),
('unmesh.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 75 DAY)),
('kalyani.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 76 DAY)),
('narendra.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 77 DAY)),
('sharada.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 78 DAY)),
('makarand.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 79 DAY)),
('anagha.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 80 DAY)),
('siddharth.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 81 DAY)),
('madhura.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 82 DAY)),
('chinmay.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 83 DAY)),
('pournima.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 84 DAY)),
('sumedh.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 85 DAY)),
('reshma.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 86 DAY)),
('aditya.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 87 DAY)),
('varsha.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 88 DAY)),
('karan.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 89 DAY)),
('nayana.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 90 DAY)),
('vedant.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 91 DAY)),
('yogita.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 92 DAY)),
('rahil.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 93 DAY)),
('samruddhi.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 94 DAY)),
('aryan.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 95 DAY)),
('tanvi.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 96 DAY)),
('veer.jadhav@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 97 DAY)),
('isha.patil@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 98 DAY)),
('arjun.kulkarni@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 99 DAY)),
('siya.joshi@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, DATE_SUB(NOW(), INTERVAL 100 DAY));

-- PROFILES (100 records)
INSERT IGNORE INTO profiles (user_id, first_name, last_name, gender, date_of_birth, marital_status, religion, caste, mother_tongue, height_cm, education, occupation, city, state, country) VALUES
(1, 'Rahul', 'Sharma', 'male', '1992-05-15', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 175, 'B.Tech', 'Software Engineer', 'Mumbai', 'Maharashtra', 'India'),
(2, 'Priya', 'Singh', 'female', '1995-08-22', 'never_married', 'Hindu', 'Rajput', 'Hindi', 163, 'MBA', 'Marketing Manager', 'Delhi', 'Delhi', 'India'),
(3, 'Amit', 'Kumar', 'male', '1990-12-10', 'never_married', 'Hindu', 'Kayastha', 'Hindi', 178, 'CA', 'Chartered Accountant', 'Bangalore', 'Karnataka', 'India'),
(4, 'Neha', 'Verma', 'female', '1993-03-18', 'never_married', 'Hindu', 'Baniya', 'Hindi', 160, 'MBBS', 'Doctor', 'Chennai', 'Tamil Nadu', 'India'),
(5, 'Vikram', 'Patel', 'male', '1988-07-25', 'never_married', 'Hindu', 'Patidar', 'Gujarati', 172, 'B.Tech', 'Business Owner', 'Ahmedabad', 'Gujarat', 'India'),
(6, 'Anita', 'Gupta', 'female', '1991-11-30', 'never_married', 'Hindu', 'Baniya', 'Hindi', 158, 'M.Com', 'Accountant', 'Jaipur', 'Rajasthan', 'India'),
(7, 'Rajesh', 'Mehta', 'male', '1989-09-12', 'divorced', 'Jain', 'Shrimali', 'Gujarati', 170, 'MBA', 'Manager', 'Mumbai', 'Maharashtra', 'India'),
(8, 'Sunita', 'Jain', 'female', '1994-04-05', 'never_married', 'Jain', 'Oswal', 'Gujarati', 162, 'B.Sc', 'Teacher', 'Surat', 'Gujarat', 'India'),
(9, 'Deepak', 'Sharma', 'male', '1991-01-20', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 176, 'M.Tech', 'Research Scientist', 'Bangalore', 'Karnataka', 'India'),
(10, 'Pooja', 'Agarwal', 'female', '1992-06-28', 'never_married', 'Hindu', 'Baniya', 'Hindi', 159, 'BBA', 'Businesswoman', 'Delhi', 'Delhi', 'India'),
(11, 'Suresh', 'Kumar', 'male', '1987-10-14', 'never_married', 'Hindu', 'Yadav', 'Hindi', 174, 'B.A', 'Government Officer', 'Lucknow', 'Uttar Pradesh', 'India'),
(12, 'Rekha', 'Singh', 'female', '1993-02-08', 'never_married', 'Sikh', 'Jat', 'Punjabi', 165, 'B.Ed', 'Teacher', 'Chandigarh', 'Punjab', 'India'),
(13, 'Manoj', 'Verma', 'male', '1990-08-19', 'never_married', 'Hindu', 'Kayastha', 'Hindi', 177, 'LLB', 'Lawyer', 'Delhi', 'Delhi', 'India'),
(14, 'Kavita', 'Rao', 'female', '1991-05-22', 'never_married', 'Hindu', 'Brahmin', 'Telugu', 161, 'B.Tech', 'Software Engineer', 'Hyderabad', 'Telangana', 'India'),
(15, 'Sunil', 'Reddy', 'male', '1989-03-11', 'never_married', 'Hindu', 'Reddy', 'Telugu', 173, 'MBBS', 'Doctor', 'Hyderabad', 'Telangana', 'India'),
(16, 'Laxmi', 'Nair', 'female', '1992-09-25', 'never_married', 'Hindu', 'Nair', 'Malayalam', 164, 'M.Sc', 'Researcher', 'Kochi', 'Kerala', 'India'),
(17, 'Ramesh', 'Iyer', 'male', '1988-12-07', 'never_married', 'Hindu', 'Iyer', 'Tamil', 171, 'CA', 'Chartered Accountant', 'Chennai', 'Tamil Nadu', 'India'),
(18, 'Meena', 'Krishnan', 'female', '1990-07-16', 'never_married', 'Hindu', 'Iyer', 'Tamil', 160, 'M.A', 'Professor', 'Chennai', 'Tamil Nadu', 'India'),
(19, 'Arun', 'Pillai', 'male', '1991-04-29', 'never_married', 'Hindu', 'Nair', 'Malayalam', 175, 'B.Tech', 'Engineer', 'Thiruvananthapuram', 'Kerala', 'India'),
(20, 'Divya', 'Menon', 'female', '1993-11-03', 'never_married', 'Hindu', 'Nair', 'Malayalam', 163, 'MBA', 'Manager', 'Kochi', 'Kerala', 'India'),
(21, 'Venkat', 'Raju', 'male', '1989-06-18', 'never_married', 'Hindu', 'Kamma', 'Telugu', 172, 'B.Tech', 'Software Engineer', 'Hyderabad', 'Telangana', 'India'),
(22, 'Sneha', 'Devi', 'female', '1992-02-24', 'never_married', 'Hindu', 'Kamma', 'Telugu', 161, 'B.D.S', 'Dentist', 'Vijayawada', 'Andhra Pradesh', 'India'),
(23, 'Krishna', 'Murthy', 'male', '1990-10-09', 'never_married', 'Hindu', 'Brahmin', 'Kannada', 174, 'M.Tech', 'Researcher', 'Bangalore', 'Karnataka', 'India'),
(24, 'Padma', 'Lakshmi', 'female', '1991-08-13', 'never_married', 'Hindu', 'Lingayat', 'Kannada', 162, 'B.Com', 'Accountant', 'Bangalore', 'Karnataka', 'India'),
(25, 'Narendra', 'Sharma', 'male', '1987-03-27', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 176, 'IAS', 'IAS Officer', 'Bhopal', 'Madhya Pradesh', 'India'),
(26, 'Savita', 'Gupta', 'female', '1993-05-31', 'never_married', 'Hindu', 'Baniya', 'Hindi', 159, 'M.A', 'Teacher', 'Varanasi', 'Uttar Pradesh', 'India'),
(27, 'Mohan', 'Singh', 'male', '1988-11-15', 'never_married', 'Sikh', 'Jat', 'Punjabi', 178, 'B.Tech', 'Army Officer', 'Jalandhar', 'Punjab', 'India'),
(28, 'Ashwini', 'Kumar', 'female', '1992-07-08', 'never_married', 'Hindu', 'Kumar', 'Hindi', 160, 'B.Sc Nursing', 'Nurse', 'Delhi', 'Delhi', 'India'),
(29, 'Pradeep', 'Yadav', 'male', '1990-01-22', 'never_married', 'Hindu', 'Yadav', 'Hindi', 173, 'B.Tech', 'Engineer', 'Kanpur', 'Uttar Pradesh', 'India'),
(30, 'Meenakshi', 'Devi', 'female', '1991-09-04', 'never_married', 'Hindu', 'Yadav', 'Hindi', 158, 'B.A', 'Teacher', 'Lucknow', 'Uttar Pradesh', 'India'),
(31, 'Ajay', 'Dubey', 'male', '1989-04-17', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 175, 'M.Sc', 'Professor', 'Allahabad', 'Uttar Pradesh', 'India'),
(32, 'Rani', 'Trivedi', 'female', '1993-12-01', 'never_married', 'Hindu', 'Brahmin', 'Gujarati', 161, 'B.Com', 'Accountant', 'Ahmedabad', 'Gujarat', 'India'),
(33, 'Vijay', 'Tiwari', 'male', '1991-06-14', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 174, 'LLB', 'Lawyer', 'Allahabad', 'Uttar Pradesh', 'India'),
(34, 'Geeta', 'Pande', 'female', '1992-02-26', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 159, 'M.A', 'Teacher', 'Delhi', 'Delhi', 'India'),
(35, 'Sanjay', 'Mishra', 'male', '1988-10-08', 'never_married', 'Hindu', 'Brahmin', 'Hindi', 176, 'B.Tech', 'Engineer', 'Lucknow', 'Uttar Pradesh', 'India'),
(36, 'Anuradha', 'Joshi', 'female', '1990-08-20', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 163, 'M.Sc', 'Professor', 'Pune', 'Maharashtra', 'India'),
(37, 'Harsh', 'Vora', 'male', '1989-03-03', 'never_married', 'Jain', 'Shrimali', 'Gujarati', 171, 'B.Com', 'Businessman', 'Surat', 'Gujarat', 'India'),
(38, 'Bhavana', 'Shah', 'female', '1991-11-16', 'never_married', 'Jain', 'Shah', 'Gujarati', 160, 'B.A', 'Homemaker', 'Ahmedabad', 'Gujarat', 'India'),
(39, 'Dinesh', 'Desai', 'male', '1990-07-29', 'never_married', 'Hindu', 'Patel', 'Gujarati', 172, 'B.Tech', 'Engineer', 'Mumbai', 'Maharashtra', 'India'),
(40, 'Jyoti', 'Kulkarni', 'female', '1992-04-12', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 162, 'MBBS', 'Doctor', 'Pune', 'Maharashtra', 'India'),
(41, 'Subhash', 'Jadhav', 'male', '1988-12-25', 'never_married', 'Hindu', 'Maratha', 'Marathi', 174, 'B.Tech', 'Engineer', 'Pune', 'Maharashtra', 'India'),
(42, 'Madhuri', 'Pawar', 'female', '1993-06-08', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'B.Com', 'Accountant', 'Mumbai', 'Maharashtra', 'India'),
(43, 'Prakash', 'Patil', 'male', '1991-02-21', 'never_married', 'Hindu', 'Maratha', 'Marathi', 175, 'MBA', 'Manager', 'Pune', 'Maharashtra', 'India'),
(44, 'Swati', 'Shinde', 'female', '1990-09-15', 'never_married', 'Hindu', 'Maratha', 'Marathi', 161, 'B.Ed', 'Teacher', 'Nashik', 'Maharashtra', 'India'),
(45, 'Mahesh', 'Kamble', 'male', '1989-05-28', 'never_married', 'Buddhist', 'Mahar', 'Marathi', 173, 'B.Tech', 'Engineer', 'Mumbai', 'Maharashtra', 'India'),
(46, 'Priyanka', 'Salve', 'female', '1992-11-10', 'never_married', 'Buddhist', 'Mahar', 'Marathi', 159, 'B.Sc', 'Lab Technician', 'Nagpur', 'Maharashtra', 'India'),
(47, 'Sandeep', 'More', 'male', '1990-08-02', 'never_married', 'Hindu', 'Maratha', 'Marathi', 176, 'M.Com', 'Bank Manager', 'Aurangabad', 'Maharashtra', 'India'),
(48, 'Archana', 'Jadhav', 'female', '1991-03-16', 'never_married', 'Hindu', 'Maratha', 'Marathi', 162, 'M.A', 'Professor', 'Kolhapur', 'Maharashtra', 'India'),
(49, 'Rahul', 'Kulkarni', 'male', '1988-10-30', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 174, 'M.Tech', 'Researcher', 'Mumbai', 'Maharashtra', 'India'),
(50, 'Nisha', 'Gore', 'female', '1993-07-13', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 160, 'B.Tech', 'Software Engineer', 'Pune', 'Maharashtra', 'India'),
(51, 'Atul', 'Patil', 'male', '1989-04-25', 'never_married', 'Hindu', 'Maratha', 'Marathi', 175, 'B.Tech', 'Engineer', 'Nagpur', 'Maharashtra', 'India'),
(52, 'Pallavi', 'Deshmukh', 'female', '1992-12-08', 'never_married', 'Hindu', 'Maratha', 'Marathi', 161, 'MBA', 'HR Manager', 'Mumbai', 'Maharashtra', 'India'),
(53, 'Nikhil', 'Suryawanshi', 'male', '1991-09-21', 'never_married', 'Hindu', 'Suryawanshi', 'Marathi', 173, 'B.Tech', 'Engineer', 'Pune', 'Maharashtra', 'India'),
(54, 'Rashmi', 'Pawar', 'female', '1990-06-04', 'never_married', 'Hindu', 'Maratha', 'Marathi', 159, 'B.Com', 'Accountant', 'Mumbai', 'Maharashtra', 'India'),
(55, 'Abhishek', 'Bhosale', 'male', '1988-11-17', 'never_married', 'Hindu', 'Maratha', 'Marathi', 176, 'LLB', 'Lawyer', 'Mumbai', 'Maharashtra', 'India'),
(56, 'Shweta', 'Kadam', 'female', '1993-02-01', 'never_married', 'Hindu', 'Maratha', 'Marathi', 162, 'B.Sc', 'Teacher', 'Thane', 'Maharashtra', 'India'),
(57, 'Rohit', 'Jadhav', 'male', '1990-07-14', 'never_married', 'Hindu', 'Maratha', 'Marathi', 174, 'MBA', 'Businessman', 'Pune', 'Maharashtra', 'India'),
(58, 'Tejaswini', 'Patil', 'female', '1991-10-27', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'BDS', 'Dentist', 'Mumbai', 'Maharashtra', 'India'),
(59, 'Omkar', 'Shinde', 'male', '1989-03-10', 'never_married', 'Hindu', 'Maratha', 'Marathi', 175, 'B.Tech', 'Engineer', 'Mumbai', 'Maharashtra', 'India'),
(60, 'Sayali', 'Kulkarni', 'female', '1992-08-23', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 161, 'M.Sc', 'Professor', 'Pune', 'Maharashtra', 'India'),
(61, 'Kiran', 'Gawade', 'male', '1991-05-06', 'never_married', 'Hindu', 'Maratha', 'Marathi', 172, 'B.Com', 'Bank Manager', 'Mumbai', 'Maharashtra', 'India'),
(62, 'Megha', 'Joshi', 'female', '1993-11-19', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 159, 'B.Tech', 'Software Engineer', 'Pune', 'Maharashtra', 'India'),
(63, 'Sachin', 'Deshpande', 'male', '1988-12-02', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 176, 'M.Tech', 'Researcher', 'Mumbai', 'Maharashtra', 'India'),
(64, 'Shraddha', 'Kulkarni', 'female', '1990-06-16', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 162, 'MBBS', 'Doctor', 'Mumbai', 'Maharashtra', 'India'),
(65, 'Prasad', 'Joshi', 'male', '1989-09-29', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 173, 'CA', 'Chartered Accountant', 'Pune', 'Maharashtra', 'India'),
(66, 'Anuja', 'Patil', 'female', '1992-04-12', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'B.A', 'Teacher', 'Solapur', 'Maharashtra', 'India'),
(67, 'Milind', 'Kulkarni', 'male', '1991-01-25', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 175, 'MBA', 'Manager', 'Mumbai', 'Maharashtra', 'India'),
(68, 'Prachi', 'Deshmukh', 'female', '1993-07-08', 'never_married', 'Hindu', 'Maratha', 'Marathi', 161, 'B.Com', 'Accountant', 'Pune', 'Maharashtra', 'India'),
(69, 'Saurabh', 'Jadhav', 'male', '1990-10-21', 'never_married', 'Hindu', 'Maratha', 'Marathi', 174, 'B.Tech', 'Engineer', 'Pune', 'Maharashtra', 'India'),
(70, 'Neelam', 'Patil', 'female', '1992-03-05', 'never_married', 'Hindu', 'Maratha', 'Marathi', 159, 'B.Ed', 'Teacher', 'Satara', 'Maharashtra', 'India'),
(71, 'Amol', 'Kulkarni', 'male', '1988-11-18', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 176, 'LLB', 'Lawyer', 'Mumbai', 'Maharashtra', 'India'),
(72, 'Vaishali', 'Joshi', 'female', '1991-06-01', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 162, 'M.Sc', 'Professor', 'Pune', 'Maharashtra', 'India'),
(73, 'Pravin', 'Deshpande', 'male', '1989-04-14', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 173, 'M.Tech', 'Engineer', 'Mumbai', 'Maharashtra', 'India'),
(74, 'Supriya', 'Patil', 'female', '1993-09-27', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'B.A', 'Social Worker', 'Pune', 'Maharashtra', 'India'),
(75, 'Unmesh', 'Kulkarni', 'male', '1990-08-10', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 175, 'CA', 'Chartered Accountant', 'Pune', 'Maharashtra', 'India'),
(76, 'Kalyani', 'Joshi', 'female', '1992-02-23', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 161, 'MBA', 'Manager', 'Mumbai', 'Maharashtra', 'India'),
(77, 'Narendra', 'Jadhav', 'male', '1989-05-07', 'never_married', 'Hindu', 'Maratha', 'Marathi', 174, 'B.Tech', 'Engineer', 'Pune', 'Maharashtra', 'India'),
(78, 'Sharada', 'Patil', 'female', '1991-11-20', 'never_married', 'Hindu', 'Maratha', 'Marathi', 159, 'B.Com', 'Accountant', 'Mumbai', 'Maharashtra', 'India'),
(79, 'Makarand', 'Kulkarni', 'male', '1988-12-03', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 176, 'M.Sc', 'Professor', 'Pune', 'Maharashtra', 'India'),
(80, 'Anagha', 'Joshi', 'female', '1993-07-16', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 162, 'B.Tech', 'Software Engineer', 'Pune', 'Maharashtra', 'India'),
(81, 'Siddharth', 'Jadhav', 'male', '1990-04-29', 'never_married', 'Hindu', 'Maratha', 'Marathi', 173, 'MBA', 'Businessman', 'Mumbai', 'Maharashtra', 'India'),
(82, 'Madhura', 'Patil', 'female', '1992-10-12', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'B.Ed', 'Teacher', 'Pune', 'Maharashtra', 'India'),
(83, 'Chinmay', 'Kulkarni', 'male', '1989-06-25', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 175, 'M.Tech', 'Researcher', 'Mumbai', 'Maharashtra', 'India'),
(84, 'Pournima', 'Joshi', 'female', '1991-02-08', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 161, 'MBBS', 'Doctor', 'Pune', 'Maharashtra', 'India'),
(85, 'Sumedh', 'Jadhav', 'male', '1990-09-21', 'never_married', 'Hindu', 'Maratha', 'Marathi', 174, 'B.Tech', 'Engineer', 'Pune', 'Maharashtra', 'India'),
(86, 'Reshma', 'Patil', 'female', '1993-05-04', 'never_married', 'Hindu', 'Maratha', 'Marathi', 159, 'B.Sc', 'Lab Technician', 'Mumbai', 'Maharashtra', 'India'),
(87, 'Aditya', 'Kulkarni', 'male', '1988-11-17', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 176, 'CA', 'Chartered Accountant', 'Pune', 'Maharashtra', 'India'),
(88, 'Varsha', 'Joshi', 'female', '1992-08-01', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 162, 'M.A', 'Professor', 'Pune', 'Maharashtra', 'India'),
(89, 'Karan', 'Jadhav', 'male', '1991-03-15', 'never_married', 'Hindu', 'Maratha', 'Marathi', 173, 'B.Tech', 'Engineer', 'Mumbai', 'Maharashtra', 'India'),
(90, 'Nayana', 'Patil', 'female', '1993-10-28', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'B.Com', 'Accountant', 'Pune', 'Maharashtra', 'India'),
(91, 'Vedant', 'Kulkarni', 'male', '1990-07-11', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 175, 'MBA', 'Manager', 'Mumbai', 'Maharashtra', 'India'),
(92, 'Yogita', 'Joshi', 'female', '1992-04-24', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 161, 'B.Tech', 'Software Engineer', 'Pune', 'Maharashtra', 'India'),
(93, 'Rahil', 'Jadhav', 'male', '1989-12-07', 'never_married', 'Hindu', 'Maratha', 'Marathi', 174, 'LLB', 'Lawyer', 'Mumbai', 'Maharashtra', 'India'),
(94, 'Samruddhi', 'Patil', 'female', '1991-06-20', 'never_married', 'Hindu', 'Maratha', 'Marathi', 159, 'B.Ed', 'Teacher', 'Pune', 'Maharashtra', 'India'),
(95, 'Aryan', 'Kulkarni', 'male', '1990-09-03', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 176, 'M.Tech', 'Engineer', 'Mumbai', 'Maharashtra', 'India'),
(96, 'Tanvi', 'Joshi', 'female', '1993-02-16', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 162, 'MBBS', 'Doctor', 'Mumbai', 'Maharashtra', 'India'),
(97, 'Veer', 'Jadhav', 'male', '1988-10-30', 'never_married', 'Hindu', 'Maratha', 'Marathi', 173, 'B.Com', 'Businessman', 'Pune', 'Maharashtra', 'India'),
(98, 'Isha', 'Patil', 'female', '1992-07-14', 'never_married', 'Hindu', 'Maratha', 'Marathi', 160, 'B.A', 'Teacher', 'Mumbai', 'Maharashtra', 'India'),
(99, 'Arjun', 'Kulkarni', 'male', '1991-04-27', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 175, 'CA', 'Chartered Accountant', 'Pune', 'Maharashtra', 'India'),
(100, 'Siya', 'Joshi', 'female', '1993-11-10', 'never_married', 'Hindu', 'Brahmin', 'Marathi', 161, 'M.Sc', 'Professor', 'Pune', 'Maharashtra', 'India');

-- PROFILE PHOTOS (100 records - 1 per user for brevity)
INSERT IGNORE INTO profile_photos (user_id, path, is_primary, privacy_level, status, caption) VALUES
(1, '/uploads/photos/user1_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(2, '/uploads/photos/user2_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(3, '/uploads/photos/user3_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(4, '/uploads/photos/user4_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(5, '/uploads/photos/user5_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(6, '/uploads/photos/user6_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(7, '/uploads/photos/user7_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(8, '/uploads/photos/user8_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(9, '/uploads/photos/user9_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(10, '/uploads/photos/user10_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(11, '/uploads/photos/user11_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(12, '/uploads/photos/user12_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(13, '/uploads/photos/user13_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(14, '/uploads/photos/user14_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(15, '/uploads/photos/user15_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(16, '/uploads/photos/user16_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(17, '/uploads/photos/user17_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(18, '/uploads/photos/user18_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(19, '/uploads/photos/user19_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(20, '/uploads/photos/user20_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(21, '/uploads/photos/user21_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(22, '/uploads/photos/user22_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(23, '/uploads/photos/user23_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(24, '/uploads/photos/user24_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(25, '/uploads/photos/user25_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(26, '/uploads/photos/user26_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(27, '/uploads/photos/user27_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(28, '/uploads/photos/user28_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(29, '/uploads/photos/user29_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(30, '/uploads/photos/user30_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(31, '/uploads/photos/user31_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(32, '/uploads/photos/user32_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(33, '/uploads/photos/user33_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(34, '/uploads/photos/user34_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(35, '/uploads/photos/user35_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(36, '/uploads/photos/user36_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(37, '/uploads/photos/user37_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(38, '/uploads/photos/user38_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(39, '/uploads/photos/user39_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(40, '/uploads/photos/user40_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(41, '/uploads/photos/user41_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(42, '/uploads/photos/user42_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(43, '/uploads/photos/user43_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(44, '/uploads/photos/user44_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(45, '/uploads/photos/user45_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(46, '/uploads/photos/user46_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(47, '/uploads/photos/user47_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(48, '/uploads/photos/user48_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(49, '/uploads/photos/user49_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(50, '/uploads/photos/user50_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(51, '/uploads/photos/user51_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(52, '/uploads/photos/user52_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(53, '/uploads/photos/user53_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(54, '/uploads/photos/user54_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(55, '/uploads/photos/user55_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(56, '/uploads/photos/user56_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(57, '/uploads/photos/user57_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(58, '/uploads/photos/user58_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(59, '/uploads/photos/user59_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(60, '/uploads/photos/user60_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(61, '/uploads/photos/user61_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(62, '/uploads/photos/user62_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(63, '/uploads/photos/user63_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(64, '/uploads/photos/user64_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(65, '/uploads/photos/user65_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(66, '/uploads/photos/user66_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(67, '/uploads/photos/user67_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(68, '/uploads/photos/user68_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(69, '/uploads/photos/user69_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(70, '/uploads/photos/user70_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(71, '/uploads/photos/user71_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(72, '/uploads/photos/user72_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(73, '/uploads/photos/user73_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(74, '/uploads/photos/user74_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(75, '/uploads/photos/user75_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(76, '/uploads/photos/user76_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(77, '/uploads/photos/user77_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(78, '/uploads/photos/user78_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(79, '/uploads/photos/user79_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(80, '/uploads/photos/user80_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(81, '/uploads/photos/user81_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(82, '/uploads/photos/user82_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(83, '/uploads/photos/user83_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(84, '/uploads/photos/user84_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(85, '/uploads/photos/user85_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(86, '/uploads/photos/user86_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(87, '/uploads/photos/user87_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(88, '/uploads/photos/user88_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(89, '/uploads/photos/user89_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(90, '/uploads/photos/user90_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(91, '/uploads/photos/user91_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(92, '/uploads/photos/user92_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(93, '/uploads/photos/user93_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(94, '/uploads/photos/user94_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(95, '/uploads/photos/user95_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(96, '/uploads/photos/user96_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(97, '/uploads/photos/user97_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(98, '/uploads/photos/user98_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(99, '/uploads/photos/user99_1.jpg', 1, 'public', 'approved', 'Main profile photo'),
(100, '/uploads/photos/user100_1.jpg', 1, 'public', 'approved', 'Main profile photo');

-- MEMBERSHIPS (50 records - random users with plans)
INSERT IGNORE INTO memberships (user_id, plan_id, starts_at, ends_at, status) VALUES
(1, 2, DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_ADD(NOW(), INTERVAL 150 DAY), 'active'),
(2, 3, DATE_SUB(NOW(), INTERVAL 60 DAY), DATE_ADD(NOW(), INTERVAL 305 DAY), 'active'),
(3, 2, DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_ADD(NOW(), INTERVAL 165 DAY), 'active'),
(4, 3, DATE_SUB(NOW(), INTERVAL 90 DAY), DATE_ADD(NOW(), INTERVAL 275 DAY), 'active'),
(5, 4, DATE_SUB(NOW(), INTERVAL 120 DAY), DATE_ADD(NOW(), INTERVAL 245 DAY), 'active'),
(6, 1, DATE_SUB(NOW(), INTERVAL 180 DAY), DATE_ADD(NOW(), INTERVAL 36365 DAY), 'active'),
(7, 3, DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_ADD(NOW(), INTERVAL 320 DAY), 'active'),
(8, 2, DATE_SUB(NOW(), INTERVAL 75 DAY), DATE_ADD(NOW(), INTERVAL 105 DAY), 'active'),
(9, 4, DATE_SUB(NOW(), INTERVAL 100 DAY), DATE_ADD(NOW(), INTERVAL 265 DAY), 'active'),
(10, 2, DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_ADD(NOW(), INTERVAL 160 DAY), 'active'),
(11, 1, DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_ADD(NOW(), INTERVAL 36345 DAY), 'active'),
(12, 3, DATE_SUB(NOW(), INTERVAL 50 DAY), DATE_ADD(NOW(), INTERVAL 315 DAY), 'active'),
(13, 2, DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_ADD(NOW(), INTERVAL 155 DAY), 'active'),
(14, 3, DATE_SUB(NOW(), INTERVAL 80 DAY), DATE_ADD(NOW(), INTERVAL 285 DAY), 'active'),
(15, 4, DATE_SUB(NOW(), INTERVAL 110 DAY), DATE_ADD(NOW(), INTERVAL 255 DAY), 'active'),
(16, 2, DATE_SUB(NOW(), INTERVAL 35 DAY), DATE_ADD(NOW(), INTERVAL 145 DAY), 'active'),
(17, 3, DATE_SUB(NOW(), INTERVAL 65 DAY), DATE_ADD(NOW(), INTERVAL 300 DAY), 'active'),
(18, 2, DATE_SUB(NOW(), INTERVAL 95 DAY), DATE_ADD(NOW(), INTERVAL 85 DAY), 'active'),
(19, 4, DATE_SUB(NOW(), INTERVAL 130 DAY), DATE_ADD(NOW(), INTERVAL 235 DAY), 'active'),
(20, 2, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 170 DAY), 'active'),
(21, 3, DATE_SUB(NOW(), INTERVAL 55 DAY), DATE_ADD(NOW(), INTERVAL 310 DAY), 'active'),
(22, 2, DATE_SUB(NOW(), INTERVAL 85 DAY), DATE_ADD(NOW(), INTERVAL 95 DAY), 'active'),
(23, 4, DATE_SUB(NOW(), INTERVAL 115 DAY), DATE_ADD(NOW(), INTERVAL 250 DAY), 'active'),
(24, 2, DATE_SUB(NOW(), INTERVAL 40 DAY), DATE_ADD(NOW(), INTERVAL 140 DAY), 'active'),
(25, 3, DATE_SUB(NOW(), INTERVAL 70 DAY), DATE_ADD(NOW(), INTERVAL 295 DAY), 'active'),
(26, 1, DATE_SUB(NOW(), INTERVAL 210 DAY), DATE_ADD(NOW(), INTERVAL 36335 DAY), 'active'),
(27, 3, DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_ADD(NOW(), INTERVAL 335 DAY), 'active'),
(28, 2, DATE_SUB(NOW(), INTERVAL 60 DAY), DATE_ADD(NOW(), INTERVAL 120 DAY), 'active'),
(29, 4, DATE_SUB(NOW(), INTERVAL 90 DAY), DATE_ADD(NOW(), INTERVAL 275 DAY), 'active'),
(30, 2, DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_ADD(NOW(), INTERVAL 165 DAY), 'active'),
(31, 3, DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_ADD(NOW(), INTERVAL 320 DAY), 'active'),
(32, 2, DATE_SUB(NOW(), INTERVAL 75 DAY), DATE_ADD(NOW(), INTERVAL 105 DAY), 'active'),
(33, 4, DATE_SUB(NOW(), INTERVAL 105 DAY), DATE_ADD(NOW(), INTERVAL 260 DAY), 'active'),
(34, 2, DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_ADD(NOW(), INTERVAL 160 DAY), 'active'),
(35, 3, DATE_SUB(NOW(), INTERVAL 50 DAY), DATE_ADD(NOW(), INTERVAL 315 DAY), 'active'),
(36, 2, DATE_SUB(NOW(), INTERVAL 80 DAY), DATE_ADD(NOW(), INTERVAL 100 DAY), 'active'),
(37, 4, DATE_SUB(NOW(), INTERVAL 110 DAY), DATE_ADD(NOW(), INTERVAL 255 DAY), 'active'),
(38, 2, DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_ADD(NOW(), INTERVAL 155 DAY), 'active'),
(39, 3, DATE_SUB(NOW(), INTERVAL 55 DAY), DATE_ADD(NOW(), INTERVAL 310 DAY), 'active'),
(40, 2, DATE_SUB(NOW(), INTERVAL 85 DAY), DATE_ADD(NOW(), INTERVAL 95 DAY), 'active'),
(41, 4, DATE_SUB(NOW(), INTERVAL 115 DAY), DATE_ADD(NOW(), INTERVAL 250 DAY), 'active'),
(42, 2, DATE_SUB(NOW(), INTERVAL 35 DAY), DATE_ADD(NOW(), INTERVAL 145 DAY), 'active'),
(43, 3, DATE_SUB(NOW(), INTERVAL 65 DAY), DATE_ADD(NOW(), INTERVAL 300 DAY), 'active'),
(44, 2, DATE_SUB(NOW(), INTERVAL 95 DAY), DATE_ADD(NOW(), INTERVAL 85 DAY), 'active'),
(45, 4, DATE_SUB(NOW(), INTERVAL 125 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), 'active'),
(46, 2, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 170 DAY), 'active'),
(47, 3, DATE_SUB(NOW(), INTERVAL 40 DAY), DATE_ADD(NOW(), INTERVAL 325 DAY), 'active'),
(48, 2, DATE_SUB(NOW(), INTERVAL 70 DAY), DATE_ADD(NOW(), INTERVAL 110 DAY), 'active'),
(49, 4, DATE_SUB(NOW(), INTERVAL 100 DAY), DATE_ADD(NOW(), INTERVAL 265 DAY), 'active'),
(50, 2, DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_ADD(NOW(), INTERVAL 150 DAY), 'active');

-- MATCHES (100 records - random interests)
INSERT IGNORE INTO matches (user_id, target_id, status) VALUES
(1, 2, 'interested'), (1, 3, 'shortlisted'), (1, 4, 'interested'), (1, 5, 'declined'),
(2, 1, 'mutual'), (2, 3, 'interested'), (2, 4, 'shortlisted'), (2, 6, 'interested'),
(3, 1, 'interested'), (3, 2, 'interested'), (3, 5, 'shortlisted'), (3, 7, 'interested'),
(4, 1, 'interested'), (4, 2, 'mutual'), (4, 6, 'interested'), (4, 8, 'shortlisted'),
(5, 1, 'declined'), (5, 3, 'interested'), (5, 7, 'interested'), (5, 9, 'shortlisted'),
(6, 2, 'interested'), (6, 4, 'interested'), (6, 8, 'interested'), (6, 10, 'shortlisted'),
(7, 3, 'interested'), (7, 5, 'interested'), (7, 9, 'interested'), (7, 11, 'shortlisted'),
(8, 4, 'shortlisted'), (8, 6, 'interested'), (8, 10, 'interested'), (8, 12, 'interested'),
(9, 5, 'shortlisted'), (9, 7, 'interested'), (9, 11, 'interested'), (9, 13, 'shortlisted'),
(10, 6, 'shortlisted'), (10, 8, 'interested'), (10, 12, 'interested'), (10, 14, 'interested'),
(11, 7, 'shortlisted'), (11, 9, 'interested'), (11, 13, 'interested'), (11, 15, 'shortlisted'),
(12, 8, 'interested'), (12, 10, 'interested'), (12, 14, 'interested'), (12, 16, 'shortlisted'),
(13, 9, 'shortlisted'), (13, 11, 'interested'), (13, 15, 'interested'), (13, 17, 'shortlisted'),
(14, 10, 'interested'), (14, 12, 'interested'), (14, 16, 'interested'), (14, 18, 'shortlisted'),
(15, 11, 'shortlisted'), (15, 13, 'interested'), (15, 17, 'interested'), (15, 19, 'shortlisted'),
(16, 12, 'shortlisted'), (16, 14, 'interested'), (16, 18, 'interested'), (16, 20, 'shortlisted'),
(17, 13, 'shortlisted'), (17, 15, 'interested'), (17, 19, 'interested'), (17, 21, 'shortlisted'),
(18, 14, 'shortlisted'), (18, 16, 'interested'), (18, 20, 'interested'), (18, 22, 'shortlisted'),
(19, 15, 'shortlisted'), (19, 17, 'interested'), (19, 21, 'interested'), (19, 23, 'shortlisted'),
(20, 16, 'shortlisted'), (20, 18, 'interested'), (20, 22, 'interested'), (20, 24, 'shortlisted'),
(21, 17, 'shortlisted'), (21, 19, 'interested'), (21, 23, 'interested'), (21, 25, 'shortlisted'),
(22, 18, 'shortlisted'), (22, 20, 'interested'), (22, 24, 'interested'), (22, 26, 'shortlisted'),
(23, 19, 'shortlisted'), (23, 21, 'interested'), (23, 25, 'interested'), (23, 27, 'shortlisted'),
(24, 20, 'shortlisted'), (24, 22, 'interested'), (24, 26, 'interested'), (24, 28, 'shortlisted'),
(25, 21, 'shortlisted'), (25, 23, 'interested'), (25, 27, 'interested'), (25, 29, 'shortlisted'),
(26, 22, 'shortlisted'), (26, 24, 'interested'), (26, 28, 'interested'), (26, 30, 'shortlisted'),
(27, 23, 'shortlisted'), (27, 25, 'interested'), (27, 29, 'interested'), (27, 31, 'shortlisted'),
(28, 24, 'shortlisted'), (28, 26, 'interested'), (28, 30, 'interested'), (28, 32, 'shortlisted'),
(29, 25, 'shortlisted'), (29, 27, 'interested'), (29, 31, 'interested'), (29, 33, 'shortlisted'),
(30, 26, 'shortlisted'), (30, 28, 'interested'), (30, 32, 'interested'), (30, 34, 'shortlisted'),
(31, 27, 'shortlisted'), (31, 29, 'interested'), (31, 33, 'interested'), (31, 35, 'shortlisted'),
(32, 28, 'shortlisted'), (32, 30, 'interested'), (32, 34, 'interested'), (32, 36, 'shortlisted'),
(33, 29, 'shortlisted'), (33, 31, 'interested'), (33, 35, 'interested'), (33, 37, 'shortlisted'),
(34, 30, 'shortlisted'), (34, 32, 'interested'), (34, 36, 'interested'), (34, 38, 'shortlisted'),
(35, 31, 'shortlisted'), (35, 33, 'interested'), (35, 37, 'interested'), (35, 39, 'shortlisted'),
(36, 32, 'shortlisted'), (36, 34, 'interested'), (36, 38, 'interested'), (36, 40, 'shortlisted'),
(37, 33, 'shortlisted'), (37, 35, 'interested'), (37, 39, 'interested'), (37, 41, 'shortlisted'),
(38, 34, 'shortlisted'), (38, 36, 'interested'), (38, 40, 'interested'), (38, 42, 'shortlisted'),
(39, 35, 'shortlisted'), (39, 37, 'interested'), (39, 41, 'interested'), (39, 43, 'shortlisted'),
(40, 36, 'shortlisted'), (40, 38, 'interested'), (40, 42, 'interested'), (40, 44, 'shortlisted'),
(41, 37, 'shortlisted'), (41, 39, 'interested'), (41, 43, 'interested'), (41, 45, 'shortlisted'),
(42, 38, 'shortlisted'), (42, 40, 'interested'), (42, 44, 'interested'), (42, 46, 'shortlisted'),
(43, 39, 'shortlisted'), (43, 41, 'interested'), (43, 45, 'interested'), (43, 47, 'shortlisted'),
(44, 40, 'shortlisted'), (44, 42, 'interested'), (44, 46, 'interested'), (44, 48, 'shortlisted'),
(45, 41, 'shortlisted'), (45, 43, 'interested'), (45, 47, 'interested'), (45, 49, 'shortlisted'),
(46, 42, 'shortlisted'), (46, 44, 'interested'), (46, 48, 'interested'), (46, 50, 'shortlisted'),
(47, 43, 'shortlisted'), (47, 45, 'interested'), (47, 49, 'interested'), (47, 51, 'shortlisted'),
(48, 44, 'shortlisted'), (48, 46, 'interested'), (48, 50, 'interested'), (48, 52, 'shortlisted'),
(49, 45, 'shortlisted'), (49, 47, 'interested'), (49, 51, 'interested'), (49, 53, 'shortlisted'),
(50, 46, 'shortlisted'), (50, 48, 'interested'), (50, 52, 'interested'), (50, 54, 'shortlisted');

-- MESSAGES (50 records)
INSERT IGNORE INTO messages (sender_id, receiver_id, body, read_at) VALUES
(1, 2, 'Hi, I liked your profile. Would like to know more about you.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(2, 1, 'Thank you for your interest. I would like to know more about you too.', DATE_SUB(NOW(), INTERVAL 12 HOUR)),
(1, 2, 'I am a software engineer working in Mumbai. What do you do?', NULL),
(3, 4, 'Hello, I found your profile interesting. Would you like to connect?', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 3, 'Hi, yes I would like to connect. Tell me more about yourself.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(5, 6, 'Hi, I am looking for a life partner. Your profile caught my attention.', NULL),
(6, 5, 'Thank you for your interest. I am also looking for a serious relationship.', NULL),
(7, 8, 'Hello, would you like to know more about me?', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(8, 7, 'Yes, I would. Please tell me about yourself and your family.', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(9, 10, 'Hi, I liked your profile. Let me know if you are interested.', NULL),
(10, 9, 'Thank you for your interest. I am open to knowing more about you.', NULL),
(11, 12, 'Hello, I am looking for a compatible partner. Your profile seems good.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(12, 11, 'Thank you. I am also looking for someone with similar values.', NULL),
(13, 14, 'Hi, I found your profile interesting. Would you like to chat?', NULL),
(14, 13, 'Hello, yes I would like to chat. What are your interests?', NULL),
(15, 16, 'Hi, I am looking for a life partner. Your profile is impressive.', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(16, 15, 'Thank you. I am also looking for a serious relationship.', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(17, 18, 'Hello, would you like to connect and know more about each other?', NULL),
(18, 17, 'Hi, yes I would like to connect. Tell me about your profession.', NULL),
(19, 20, 'Hi, I liked your profile. Let me know if you are interested to connect.', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(20, 19, 'Thank you for your interest. I am open to knowing more about you.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(21, 22, 'Hello, I am looking for a compatible partner. Your profile seems good.', NULL),
(22, 21, 'Thank you. I am also looking for someone with similar values.', NULL),
(23, 24, 'Hi, I found your profile interesting. Would you like to chat?', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(24, 23, 'Hello, yes I would like to chat. What are your hobbies?', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(25, 26, 'Hi, I am looking for a life partner. Your profile is impressive.', NULL),
(26, 25, 'Thank you. I am also looking for a serious relationship.', NULL),
(27, 28, 'Hello, would you like to connect and know more about each other?', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(28, 27, 'Hi, yes I would like to connect. Tell me about your family.', NULL),
(29, 30, 'Hi, I liked your profile. Let me know if you are interested to connect.', NULL),
(30, 29, 'Thank you for your interest. I am open to knowing more about you.', NULL),
(31, 32, 'Hello, I am looking for a compatible partner. Your profile seems good.', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(32, 31, 'Thank you. I am also looking for someone with similar values.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(33, 34, 'Hi, I found your profile interesting. Would you like to chat?', NULL),
(34, 33, 'Hello, yes I would like to chat. What are your interests?', NULL),
(35, 36, 'Hi, I am looking for a life partner. Your profile is impressive.', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(36, 35, 'Thank you. I am also looking for a serious relationship.', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(37, 38, 'Hello, would you like to connect and know more about each other?', NULL),
(38, 37, 'Hi, yes I would like to connect. Tell me about your profession.', NULL),
(39, 40, 'Hi, I liked your profile. Let me know if you are interested to connect.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(40, 39, 'Thank you for your interest. I am open to knowing more about you.', NULL),
(41, 42, 'Hello, I am looking for a compatible partner. Your profile seems good.', NULL),
(42, 41, 'Thank you. I am also looking for someone with similar values.', NULL),
(43, 44, 'Hi, I found your profile interesting. Would you like to chat?', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(44, 43, 'Hello, yes I would like to chat. What are your hobbies?', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(45, 46, 'Hi, I am looking for a life partner. Your profile is impressive.', NULL),
(46, 45, 'Thank you. I am also looking for a serious relationship.', NULL),
(47, 48, 'Hello, would you like to connect and know more about each other?', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(48, 47, 'Hi, yes I would like to connect. Tell me about your family.', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(49, 50, 'Hi, I liked your profile. Let me know if you are interested to connect.', NULL),
(50, 49, 'Thank you for your interest. I am open to knowing more about you.', NULL);

-- PROFILE VIEWS (100 records)
INSERT IGNORE INTO profile_views (viewer_id, profile_id, viewed_at) VALUES
(2, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
(3, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
(4, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
(5, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
(1, 2, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
(3, 2, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
(4, 2, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
(6, 2, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
(1, 3, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
(2, 3, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
(5, 3, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
(7, 3, DATE_SUB(NOW(), INTERVAL 7 HOUR)),
(1, 4, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
(2, 4, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
(3, 4, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
(8, 4, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
(1, 5, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
(2, 5, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
(4, 5, DATE_SUB(NOW(), INTERVAL 7 HOUR)),
(9, 5, DATE_SUB(NOW(), INTERVAL 9 HOUR)),
(6, 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(7, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(8, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(9, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(10, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(7, 2, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(8, 2, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(9, 2, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(11, 2, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(8, 3, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(9, 3, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(10, 3, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(12, 3, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(9, 4, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(10, 4, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(11, 4, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(13, 4, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(10, 5, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(11, 5, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(12, 5, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(14, 5, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(11, 6, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(12, 6, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(13, 6, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(15, 6, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(12, 7, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(13, 7, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(14, 7, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(16, 7, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(13, 8, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(14, 8, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(15, 8, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(17, 8, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(14, 9, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(15, 9, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(16, 9, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(18, 9, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(15, 10, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(16, 10, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(17, 10, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(19, 10, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(16, 11, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(17, 11, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(18, 11, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(20, 11, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(17, 12, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(18, 12, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(19, 12, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(21, 12, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(18, 13, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(19, 13, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(20, 13, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(22, 13, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(19, 14, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(20, 14, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(21, 14, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(23, 14, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(20, 15, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(21, 15, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(22, 15, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(24, 15, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(21, 16, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(22, 16, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(23, 16, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(25, 16, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(22, 17, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(23, 17, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(24, 17, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(26, 17, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(23, 18, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(24, 18, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(25, 18, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(27, 18, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(24, 19, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(25, 19, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(26, 19, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(28, 19, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(25, 20, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(26, 20, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(27, 20, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(29, 20, DATE_SUB(NOW(), INTERVAL 4 DAY));

-- PRIVACY SETTINGS (100 records)
INSERT IGNORE INTO privacy_settings (user_id, profile_visibility, show_phone, show_email, show_photos, show_online_status, receive_interests, privacy_preset) VALUES
(1, 1, 1, 0, 1, 1, 1, 'members'),
(2, 1, 1, 0, 1, 1, 1, 'members'),
(3, 1, 1, 0, 1, 1, 1, 'members'),
(4, 1, 1, 0, 1, 1, 1, 'members'),
(5, 1, 1, 0, 1, 1, 1, 'members'),
(6, 1, 1, 0, 1, 1, 1, 'members'),
(7, 1, 1, 0, 1, 1, 1, 'members'),
(8, 1, 1, 0, 1, 1, 1, 'members'),
(9, 1, 1, 0, 1, 1, 1, 'members'),
(10, 1, 1, 0, 1, 1, 1, 'members'),
(11, 1, 1, 0, 1, 1, 1, 'members'),
(12, 1, 1, 0, 1, 1, 1, 'members'),
(13, 1, 1, 0, 1, 1, 1, 'members'),
(14, 1, 1, 0, 1, 1, 1, 'members'),
(15, 1, 1, 0, 1, 1, 1, 'members'),
(16, 1, 1, 0, 1, 1, 1, 'members'),
(17, 1, 1, 0, 1, 1, 1, 'members'),
(18, 1, 1, 0, 1, 1, 1, 'members'),
(19, 1, 1, 0, 1, 1, 1, 'members'),
(20, 1, 1, 0, 1, 1, 1, 'members'),
(21, 1, 1, 0, 1, 1, 1, 'members'),
(22, 1, 1, 0, 1, 1, 1, 'members'),
(23, 1, 1, 0, 1, 1, 1, 'members'),
(24, 1, 1, 0, 1, 1, 1, 'members'),
(25, 1, 1, 0, 1, 1, 1, 'members'),
(26, 1, 1, 0, 1, 1, 1, 'members'),
(27, 1, 1, 0, 1, 1, 1, 'members'),
(28, 1, 1, 0, 1, 1, 1, 'members'),
(29, 1, 1, 0, 1, 1, 1, 'members'),
(30, 1, 1, 0, 1, 1, 1, 'members'),
(31, 1, 1, 0, 1, 1, 1, 'members'),
(32, 1, 1, 0, 1, 1, 1, 'members'),
(33, 1, 1, 0, 1, 1, 1, 'members'),
(34, 1, 1, 0, 1, 1, 1, 'members'),
(35, 1, 1, 0, 1, 1, 1, 'members'),
(36, 1, 1, 0, 1, 1, 1, 'members'),
(37, 1, 1, 0, 1, 1, 1, 'members'),
(38, 1, 1, 0, 1, 1, 1, 'members'),
(39, 1, 1, 0, 1, 1, 1, 'members'),
(40, 1, 1, 0, 1, 1, 1, 'members'),
(41, 1, 1, 0, 1, 1, 1, 'members'),
(42, 1, 1, 0, 1, 1, 1, 'members'),
(43, 1, 1, 0, 1, 1, 1, 'members'),
(44, 1, 1, 0, 1, 1, 1, 'members'),
(45, 1, 1, 0, 1, 1, 1, 'members'),
(46, 1, 1, 0, 1, 1, 1, 'members'),
(47, 1, 1, 0, 1, 1, 1, 'members'),
(48, 1, 1, 0, 1, 1, 1, 'members'),
(49, 1, 1, 0, 1, 1, 1, 'members'),
(50, 1, 1, 0, 1, 1, 1, 'members'),
(51, 1, 1, 0, 1, 1, 1, 'members'),
(52, 1, 1, 0, 1, 1, 1, 'members'),
(53, 1, 1, 0, 1, 1, 1, 'members'),
(54, 1, 1, 0, 1, 1, 1, 'members'),
(55, 1, 1, 0, 1, 1, 1, 'members'),
(56, 1, 1, 0, 1, 1, 1, 'members'),
(57, 1, 1, 0, 1, 1, 1, 'members'),
(58, 1, 1, 0, 1, 1, 1, 'members'),
(59, 1, 1, 0, 1, 1, 1, 'members'),
(60, 1, 1, 0, 1, 1, 1, 'members'),
(61, 1, 1, 0, 1, 1, 1, 'members'),
(62, 1, 1, 0, 1, 1, 1, 'members'),
(63, 1, 1, 0, 1, 1, 1, 'members'),
(64, 1, 1, 0, 1, 1, 1, 'members'),
(65, 1, 1, 0, 1, 1, 1, 'members'),
(66, 1, 1, 0, 1, 1, 1, 'members'),
(67, 1, 1, 0, 1, 1, 1, 'members'),
(68, 1, 1, 0, 1, 1, 1, 'members'),
(69, 1, 1, 0, 1, 1, 1, 'members'),
(70, 1, 1, 0, 1, 1, 1, 'members'),
(71, 1, 1, 0, 1, 1, 1, 'members'),
(72, 1, 1, 0, 1, 1, 1, 'members'),
(73, 1, 1, 0, 1, 1, 1, 'members'),
(74, 1, 1, 0, 1, 1, 1, 'members'),
(75, 1, 1, 0, 1, 1, 1, 'members'),
(76, 1, 1, 0, 1, 1, 1, 'members'),
(77, 1, 1, 0, 1, 1, 1, 'members'),
(78, 1, 1, 0, 1, 1, 1, 'members'),
(79, 1, 1, 0, 1, 1, 1, 'members'),
(80, 1, 1, 0, 1, 1, 1, 'members'),
(81, 1, 1, 0, 1, 1, 1, 'members'),
(82, 1, 1, 0, 1, 1, 1, 'members'),
(83, 1, 1, 0, 1, 1, 1, 'members'),
(84, 1, 1, 0, 1, 1, 1, 'members'),
(85, 1, 1, 0, 1, 1, 1, 'members'),
(86, 1, 1, 0, 1, 1, 1, 'members'),
(87, 1, 1, 0, 1, 1, 1, 'members'),
(88, 1, 1, 0, 1, 1, 1, 'members'),
(89, 1, 1, 0, 1, 1, 1, 'members'),
(90, 1, 1, 0, 1, 1, 1, 'members'),
(91, 1, 1, 0, 1, 1, 1, 'members'),
(92, 1, 1, 0, 1, 1, 1, 'members'),
(93, 1, 1, 0, 1, 1, 1, 'members'),
(94, 1, 1, 0, 1, 1, 1, 'members'),
(95, 1, 1, 0, 1, 1, 1, 'members'),
(96, 1, 1, 0, 1, 1, 1, 'members'),
(97, 1, 1, 0, 1, 1, 1, 'members'),
(98, 1, 1, 0, 1, 1, 1, 'members'),
(99, 1, 1, 0, 1, 1, 1, 'members'),
(100, 1, 1, 0, 1, 1, 1, 'members');

-- ACTIVITY LOG (50 records)
INSERT IGNORE INTO activity_log (user_id, action, details) VALUES
(1, 'profile_updated', '{"fields": ["education", "occupation"]}'),
(2, 'profile_viewed', '{"viewer_id": 1}'),
(3, 'interest_sent', '{"target_id": 4}'),
(4, 'interest_received', '{"sender_id": 3}'),
(5, 'photo_uploaded', '{"photo_count": 1}'),
(6, 'profile_updated', '{"fields": ["city", "state"]}'),
(7, 'shortlist_added', '{"target_id": 8}'),
(8, 'message_sent', '{"receiver_id": 7}'),
(9, 'message_received', '{"sender_id": 10}'),
(10, 'privacy_updated', '{"setting": "show_phone"}'),
(11, 'profile_viewed', '{"viewer_id": 12}'),
(12, 'interest_sent', '{"target_id": 13}'),
(13, 'profile_updated', '{"fields": ["about_me"]}'),
(14, 'photo_uploaded', '{"photo_count": 1}'),
(15, 'shortlist_added', '{"target_id": 16}'),
(16, 'message_received', '{"sender_id": 15}'),
(17, 'profile_viewed', '{"viewer_id": 18}'),
(18, 'interest_sent', '{"target_id": 19}'),
(19, 'profile_updated', '{"fields": ["occupation"]}'),
(20, 'privacy_updated', '{"setting": "show_email"}'),
(21, 'message_sent', '{"receiver_id": 22}'),
(22, 'message_received', '{"sender_id": 21}'),
(23, 'shortlist_added', '{"target_id": 24}'),
(24, 'profile_viewed', '{"viewer_id": 25}'),
(25, 'interest_sent', '{"target_id": 26}'),
(26, 'profile_updated', '{"fields": ["education"]}'),
(27, 'photo_uploaded', '{"photo_count": 1}'),
(28, 'message_sent', '{"receiver_id": 27}'),
(29, 'message_received', '{"sender_id": 30}'),
(30, 'privacy_updated', '{"setting": "show_photos"}'),
(31, 'profile_viewed', '{"viewer_id": 32}'),
(32, 'interest_sent', '{"target_id": 33}'),
(33, 'shortlist_added', '{"target_id": 34}'),
(34, 'profile_updated', '{"fields": ["city"]}'),
(35, 'message_received', '{"sender_id": 36}'),
(36, 'profile_viewed', '{"viewer_id": 37}'),
(37, 'interest_sent', '{"target_id": 38}'),
(38, 'photo_uploaded', '{"photo_count": 1}'),
(39, 'message_sent', '{"receiver_id": 40}'),
(40, 'privacy_updated', '{"setting": "receive_interests"}'),
(41, 'profile_viewed', '{"viewer_id": 42}'),
(42, 'interest_sent', '{"target_id": 43}'),
(43, 'shortlist_added', '{"target_id": 44}'),
(44, 'profile_updated', '{"fields": ["occupation"]}'),
(45, 'message_received', '{"sender_id": 46}'),
(46, 'profile_viewed', '{"viewer_id": 47}'),
(47, 'interest_sent', '{"target_id": 48}'),
(48, 'photo_uploaded', '{"photo_count": 1}'),
(49, 'message_sent', '{"receiver_id": 50}'),
(50, 'privacy_updated', '{"setting": "profile_visibility"}');

-- PROFILE SEARCHES (25 records)
INSERT IGNORE INTO profile_searches (user_id, name, filters_json, alert_enabled) VALUES
(1, 'Software Engineers', '{"age_min": 25, "age_max": 32, "education": ["B.Tech", "M.Tech"], "occupation": ["Software Engineer"]}', 1),
(2, 'Doctors in Delhi', '{"age_min": 26, "age_max": 35, "education": ["MBBS", "MD"], "city": "Delhi"}', 1),
(3, 'CA Professionals', '{"age_min": 24, "age_max": 32, "education": ["CA"], "occupation": ["Chartered Accountant"]}', 0),
(4, 'MBA Graduates', '{"age_min": 25, "age_max": 35, "education": ["MBA"], "occupation": ["Manager"]}', 1),
(5, 'Government Officers', '{"age_min": 28, "age_max": 40, "occupation": ["Government Officer", "IAS"]}', 0),
(6, 'Teachers', '{"age_min": 24, "age_max": 35, "education": ["B.Ed", "M.A"], "occupation": ["Teacher", "Professor"]}', 1),
(7, 'Engineers in Mumbai', '{"age_min": 25, "age_max": 32, "education": ["B.Tech", "M.Tech"], "city": "Mumbai"}', 1),
(8, 'Business Owners', '{"age_min": 28, "age_max": 45, "occupation": ["Businessman", "Business Owner"]}', 0),
(9, 'Bank Managers', '{"age_min": 26, "age_max": 35, "occupation": ["Bank Manager"]}', 1),
(10, 'IT Professionals', '{"age_min": 24, "age_max": 32, "occupation": ["Software Engineer", "Engineer"]}', 1),
(11, 'Medical Professionals', '{"age_min": 25, "age_max": 35, "education": ["MBBS", "BDS", "MD"], "occupation": ["Doctor", "Dentist"]}', 0),
(12, 'Army Officers', '{"age_min": 26, "age_max": 35, "occupation": ["Army Officer"]}', 1),
(13, 'Professors', '{"age_min": 28, "age_max": 45, "education": ["PhD", "M.A", "M.Sc"], "occupation": ["Professor"]}', 0),
(14, 'Accountants', '{"age_min": 24, "age_max": 32, "occupation": ["Accountant", "CA"]}', 1),
(15, 'Lawyers', '{"age_min": 26, "age_max": 40, "education": ["LLB", "LLM"], "occupation": ["Lawyer"]}', 1),
(16, 'Nurses', '{"age_min": 22, "age_max": 30, "education": ["B.Sc Nursing"], "occupation": ["Nurse"]}', 0),
(17, 'Scientists', '{"age_min": 26, "age_max": 35, "education": ["M.Tech", "PhD"], "occupation": ["Researcher", "Scientist"]}', 1),
(18, 'Social Workers', '{"age_min": 24, "age_max": 35, "occupation": ["Social Worker"]}', 0),
(19, 'Homemakers', '{"age_min": 22, "age_max": 35, "occupation": ["Homemaker"]}', 1),
(20, 'Bangalore Profiles', '{"age_min": 24, "age_max": 32, "city": "Bangalore"}', 1),
(21, 'Pune Professionals', '{"age_min": 25, "age_max": 35, "city": "Pune"}', 0),
(22, 'Hyderabad IT', '{"age_min": 24, "age_max": 32, "city": "Hyderabad", "occupation": ["Software Engineer"]}', 1),
(23, 'Chennai Profiles', '{"age_min": 24, "age_max": 32, "city": "Chennai"}', 0),
(24, 'Delhi NCR', '{"age_min": 25, "age_max": 35, "city": ["Delhi", "Noida", "Gurgaon"]}', 1),
(25, 'Mumbai Metro', '{"age_min": 24, "age_max": 32, "city": "Mumbai"}', 1);
